services:
  - type: web
    name: summertec
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000